ament_prepend_unique_value GAZEBO_MODEL_PATH "/psd_ws/install/ros_components_description/share"
ament_prepend_unique_value GZ_SIM_RESOURCE_PATH "/psd_ws/install/ros_components_description/share"
ament_prepend_unique_value IGN_GAZEBO_RESOURCE_PATH "/psd_ws/install/ros_components_description/share"
