<?xml version="1.0"?>

<!--
# Copyright 2023 Intel Corporation. All Rights Reserved.
# Copyright 2023 Husarion. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->

<robot name="intel_realsense_d435" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="intel_realsense_d435"
    params="parent_link xyz rpy
            tf_prefix:=None
            name:=camera
            topic:=camera
            use_nominal_extrinsics:=false
            namespace:=None
            simulation_engine:=ignition-gazebo">

    <xacro:if value="${namespace == 'None'}">
      <xacro:property name="ns" value="" />
    </xacro:if>
    <xacro:unless value="${namespace == 'None'}">
        <xacro:property name="ns" value="${namespace}/" />
    </xacro:unless>

    <xacro:if value="${tf_prefix == 'None'}">
      <xacro:property name="prefix" value="" />
    </xacro:if>
    <xacro:unless value="${tf_prefix == 'None'}">
      <xacro:property name="prefix" value="${tf_prefix}_" />
    </xacro:unless>

    <!-- The following values are approximate, and the camera node
      publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d435_cam_depth_to_infra1_offset" value="0.0" />
    <xacro:property name="d435_cam_depth_to_infra2_offset" value="-0.050" />
    <xacro:property name="d435_cam_depth_to_color_offset" value="0.015" />

    <!-- The following values model the aluminum peripherial case for the
      D435 camera, with the camera joint represented by the actual
      peripherial camera tripod mount -->
    <xacro:property name="d435_cam_width" value="0.090" />
    <xacro:property name="d435_cam_height" value="0.025" />
    <xacro:property name="d435_cam_depth" value="0.02505" />
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149" />
    <!-- glass cover is 0.1 mm inwards from front aluminium plate -->
    <xacro:property name="d435_glass_to_front" value="0.0001" />
    <!-- see datasheet Revision 007, Fig. 4-4 page 65 -->
    <xacro:property name="d435_zero_depth_to_glass" value="0.0042" />
    <!-- convenience precomputation to avoid clutter-->
    <xacro:property name="d435_mesh_x_offset"
      value="${d435_cam_mount_from_center_offset-d435_glass_to_front-d435_zero_depth_to_glass}" />

    <!-- The following offset is relative the the physical D435 camera peripherial
      camera tripod mount -->
    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}" />
    <xacro:property name="d435_collision_offset_x" value="0.00824" />
    <xacro:property name="d435_cam_depth_py" value="0.0175" />
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}" />

    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${parent_link.rstrip('_link')}_to_${prefix}${name}_bottom_screw_joint" type="fixed">
      <origin xyz="${xyz}" rpy="${rpy}" />
      <parent link="${parent_link}" />
      <child link="${prefix}${name}_bottom_screw_frame" />
    </joint>

    <link name="${prefix}${name}_bottom_screw_frame" />

    <joint name="${prefix}${name}_bottom_screw_to_${prefix}${name}_joint" type="fixed">
      <origin xyz="${d435_mesh_x_offset} ${d435_cam_depth_py} ${d435_cam_depth_pz}"
        rpy="0.0 0.0 0.0" />
      <parent link="${prefix}${name}_bottom_screw_frame" />
      <child link="${prefix}${name}_link" />
    </joint>

    <link name="${prefix}${name}_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <geometry>
          <mesh filename="package://ros_components_description/meshes/intel_realsense_d435.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${-d435_collision_offset_x} ${-d435_cam_depth_py} 0.0" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}" />
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.072" />
        <origin xyz="0.0 0.0 0.0" />
        <inertia ixx="0.003881243" ixy="0.0"         ixz="0.0"
                                   iyy="0.000498940" iyz="0.0"
                                                     izz="0.003879257" />
      </inertial>
    </link>

    <!-- Use the nominal extrinsics between camera frames if the calibrated extrinsics aren't being
      published. e.g. running the device in simulation  -->
    <xacro:if value="${use_nominal_extrinsics}">
      <!-- camera depth joints and links -->
      <joint name="${prefix}${name}_to_${prefix}${name}_depth_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <parent link="${prefix}${name}_link" />
        <child link="${prefix}${name}_depth_frame" />
      </joint>

      <link name="${prefix}${name}_depth_frame" />

      <joint name="${prefix}${name}_depth_to_${prefix}${name}_depth_optical_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="${-pi/2.0} 0.0 ${-pi/2.0}" />
        <parent link="${prefix}${name}_depth_frame" />
        <child link="${prefix}${name}_depth_optical_frame" />
      </joint>

      <link name="${prefix}${name}_depth_optical_frame" />

      <!-- camera left IR joints and links -->
      <joint name="${prefix}${name}_to_${prefix}${name}_infra1_joint" type="fixed">
        <origin xyz="0.0 ${d435_cam_depth_to_infra1_offset} 0.0" rpy="0.0 0.0 0.0" />
        <parent link="${prefix}${name}_link" />
        <child link="${prefix}${name}_infra1_frame" />
      </joint>

      <link name="${prefix}${name}_infra1_frame" />

      <joint name="${prefix}${name}_infra1_to_${prefix}${name}_infra1_optical_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="${-pi/2.0} 0.0 ${-pi/2.0}" />
        <parent link="${prefix}${name}_infra1_frame" />
        <child link="${prefix}${name}_infra1_optical_frame" />
      </joint>

      <link name="${prefix}${name}_infra1_optical_frame" />

      <!-- camera right IR joints and links -->
      <joint name="${prefix}${name}_to_${prefix}${name}_infra2_joint" type="fixed">
        <origin xyz="0.0 ${d435_cam_depth_to_infra2_offset} 0.0" rpy="0.0 0.0 0.0" />
        <parent link="${prefix}${name}_link" />
        <child link="${prefix}${name}_infra2_frame" />
      </joint>

      <link name="${prefix}${name}_infra2_frame" />

      <joint name="${prefix}${name}_infra2_to_${prefix}${name}_infra2_optical_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="${-pi/2.0} 0.0 ${-pi/2.0}" />
        <parent link="${prefix}${name}_infra2_frame" />
        <child link="${prefix}${name}_infra2_optical_frame" />
      </joint>

      <link name="${prefix}${name}_infra2_optical_frame" />

      <!-- camera color joints and links -->
      <joint name="${prefix}${name}_to_${prefix}${name}_color_joint" type="fixed">
        <origin xyz="0.0 ${d435_cam_depth_to_color_offset} 0.0" rpy="0.0 0.0 0.0" />
        <parent link="${prefix}${name}_link" />
        <child link="${prefix}${name}_color_frame" />
      </joint>

      <link name="${prefix}${name}_color_frame" />

      <joint name="${prefix}${name}_color_to_${prefix}${name}_color_optical_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="${-pi/2.0} 0.0 ${-pi/2.0}" />
        <parent link="${prefix}${name}_color_frame" />
        <child link="${prefix}${name}_color_optical_frame" />
      </joint>

      <link name="${prefix}${name}_color_optical_frame" />
    </xacro:if>

    <xacro:if value="${simulation_engine == 'ignition-gazebo'}">
      <!-- It is also possible to use single rgbd_camera sensor, but using separate rgb and depth camera
        should be more accurate for D435 - different frames and fovs can be set -->
      <gazebo reference="${prefix}${name}_link">
        <!-- https://github.com/IntelRealSense/realsense-ros#published-topics -->
        <sensor type="camera" name="${ns}{prefix}${name}_intel_realsense_d435_color">
          <always_on>true</always_on>
          <update_rate>30.0</update_rate>

          <topic>${ns}${topic}/color/image_raw</topic>
          <visualize>false</visualize>

          <ignition_frame_id>${prefix}${name}_color_optical_frame</ignition_frame_id>
          <horizontal_fov>${69.0/180.0*pi}</horizontal_fov>
          <image>
            <width>1280</width>
            <height>720</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300.0</far>
          </clip>
          <ros>
            <namespace>${ns}</namespace>
          </ros>
        </sensor>

        <sensor type="depth_camera" name="${ns}${prefix}${name}_intel_realsense_d435_depth">
          <always_on>true</always_on>
          <update_rate>30.0</update_rate>

          <topic>${ns}${topic}/depth/image_rect_raw</topic>
          <visualize>false</visualize>

          <ignition_frame_id>${prefix}${name}_depth_optical_frame</ignition_frame_id>
          <camera>
            <horizontal_fov>${87.0/180.0*pi}</horizontal_fov>
            <image>
              <width>1280</width>
              <height>720</height>
              <format>R_FLOAT32</format>
            </image>
            <clip>
              <near>0.28</near>
              <far>8.0</far>
            </clip>
            <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.005</stddev>
            </noise>
          </camera>
          <ros>
            <namespace>${ns}</namespace>
          </ros>
        </sensor>
      </gazebo>
    </xacro:if>
  </xacro:macro>
</robot>
